# Generated by Django 6.0.4 on 2026-04-19 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.group')),
            ],
            options={
                'ordering': ('group__name', 'person1__user__username', 'person2__user__username'),
            },
        ),
        migrations.CreateModel(
            name='PairState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.IntegerField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.pair')),
            ],
            options={
                'ordering': ('pair',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_person1', to='match.person'),
        ),
        migrations.AddField(
            model_name='pair',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_person2', to='match.person'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.person'),
        ),
        migrations.AddField(
            model_name='group',
            name='people',
            field=models.ManyToManyField(related_name='group_people', to='match.person'),
        ),
        migrations.CreateModel(
            name='PersonState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmatched_count', models.IntegerField()),
                ('crowd_count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.person')),
            ],
            options={
                'ordering': ('group', 'person'),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.group')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_person1', to='match.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_person2', to='match.person')),
                ('person3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_person3', to='match.person')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.result')),
            ],
            options={
                'ordering': ('result', 'person1', 'person2', 'person3'),
            },
        ),
    ]
