# Generated by Django 6.0.4 on 2026-04-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_person1', to='match.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_person2', to='match.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='person3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_person3', to='match.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.result'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.group'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_person1', to='match.person'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_person2', to='match.person'),
        ),
        migrations.AlterField(
            model_name='pairstate',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.pair'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.group'),
        ),
        migrations.AlterField(
            model_name='personstate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.person'),
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.group'),
        ),
    ]
