# Generated by Django 6.0.4 on 2026-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_group_owner_alter_match_person1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='group_people', to='match.person'),
        ),
    ]
