# Generated by Django 6.0.4 on 2026-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_group_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to='match.person'),
        ),
    ]
